### ISSUE TITLE
need some guidence 

### ISSUE THREAD

**Issue by GGGIsGGG** [HowYouDoinMate/RedDeadRedemption2-Cheat#1]
could auther offer a guidence please?  i dont know how to use it.
many thanks

**Comment by HowYouDoinMate** [comment]
What do you want to do?

**Comment by GGGIsGGG** [comment]
Sorry for my late reply! Inject the dll to use. But I can't find the key to open the Menu.

**Comment by HowYouDoinMate** [comment]
It is F5 by default.

**Comment by GGGIsGGG** [comment]
It's OK! Many thanks! @HowYouDoinMate
